### ISSUE TITLE
How to set up AWS S3 for file storage

### ISSUE THREAD

**Issue by gksander** [drlippman/IMathAS#124]
I'm looking to use S3 for file storage for IMathAS, but I'm having a rough time getting it to work. Does anyone have suggestions for how to configure an S3 bucket (and policy/permissions) to get things working?

Here's what I've tried.

1. Allowing public permissions to read/write, just to make sure things were working on IMathAS's end. That was fine.
2. In config.php, provided the root-user access key, secret key, and bucket name. No luck here using the root-user credentials. I keep getting a putObject() [access denied] error. 
3. I tried creating a user through the IAM system and changing its policy so that it had admin access to the S3 bucket. (I tried using an IAM policy, and a Bucket policy.) Provided those credentials to `config.php` but still no luck. Still got the putObject() [access denied] error.

I'm guessing I'm doing something wrong on the AWS S3 side of things, but I'm really stumped by the fact that the root user credentials (that has full access to the bucket) won't allow me to upload through IMathAS. Perhaps someone here will share with me how they went about setting up their AWS bucket.

**Comment by gksander** [comment]
Welp, not sure what was going on - but my root-user credentials _now_ work.

I'm still a little curious: is it better to use root-user credentials, or set up an IAM/alias user for the S3 integration?

**Comment by drlippman** [comment]
I think it's considered better practice use an IAM user with limited permissions for such things, so that if the access keys get compromised, the rights the user has are limited. 

I think you figured this out, but just to be clear, the credentials you supply IMathAS in the config.php file should _not_ be the root-user or IAM user's username and password.  Instead, you want to find the user in the IAM console, select "Security Credentials" and "Create access key".  That key/secret is what IMathAS needs.

**Comment by gksander** [comment]
Okay, that's what I figured. And yes - I've been using the access key/secret key.

Thanks for the input! Closing this issue now.
