### ISSUE TITLE
admin/approvepending.php

### ISSUE THREAD

**Issue by timpersson** [drlippman/IMathAS#13]
Is the /admin/approvepending.php missing from the repository? I received an email request from a teacher using the link to newinstructor.php on the main index index page. After trying to view the request on the admin   Home > Admin > Utilities    page, Approve Pending Instructor Accounts gives a 404 error. I couldn't find the file anywhere and was just wondering if it was left out for some reason?

**Comment by drlippman** [comment]
It is a very site-personalized script, and I never got around to making a generic version.  I guess I should do that, since I think I removed the other way of looking up pending requests. 

    On Tuesday, January 19, 2016 6:33 PM, timpersson <notifications@github.com> wrote:
 

 Is the /admin/approvependingphp missing from the repository? I received an email request from a teacher using the link to newinstructorphp on the main index index page After trying to view the request on the admin Home > Admin > Utilities page, Approve Pending Instructor Accounts gives a 404 error I couldn't find the file anywhere and was just wondering if it was left out for some reason? —

**Comment by drlippman** [comment]
I just realized that the original way to approving accounts wasn't intentionally removed, it was a bug.  I just fixed that, so at least now you should be able to approve accounts that way: From the admin page Groups pulldown at the bottom, picking "Pending" to list pending users, then change their rights to give them instructor access and assign them to a group.

**Comment by drlippman** [comment]
I've got a generic approvepending.php added in the repo now.

**Comment by timpersson** [comment]
Thanks for the update. Tim 


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------
