### ISSUE TITLE
Error importing Course Items

### ISSUE THREAD

**Issue by ceh320** [drlippman/IMathAS#132]
Hi, we're getting an http 500 error when trying to import Course Items.  The error log reads:

PHP Parse error:  syntax error, unexpected '[' in /var/www/html/public/admin/importitemsfuncs.php on line 831, referer: https://dev.imathas.math.northwestern.edu/course/course.php?folder=0&cid=4

PHP Stack trace:, referer: https://dev.imathas.math.northwestern.edu/course/course.php?folder=0&cid=4

PHP   1. {main}() /var/www/html/public/admin/importitems2.php:0, referer: https://dev.imathas.math.northwestern.edu/course/course.php?folder=0&cid=4

Any help is greatly appreciated.

Thanks,

Carlos

**Comment by gksander** [comment]
I helped someone with this the other day - and it turned out that upgrading the PHP version on the server did the trick. Looks like *maybe* has something to do with using array shorthand syntax (`[...]` instead of `array(...)`). You might check your version of PHP. If it's earlier than 5.4, you might try upgrading to at least 5.4 (although PHP 7 is a nice upgrade and IMathAS runs really well on it).

Doesn't look like this is the case (based on the error message), but you might also want to make sure that Apache can write to the folder `/admin/import`.

**Comment by ceh320** [comment]
Thanks for your help. Installed PHP 7 and it works.

**Comment by drlippman** [comment]
Looks like the error is actually a missing `$this->`.  I'll get it fixed - thanks!
