### ISSUE TITLE
admin page list users

### ISSUE THREAD

**Issue by ericvanboven** [drlippman/IMathAS#14]
Used to be able to select the dropdown box under the listing of the users on the admin page and it used to have A-Z letters to be able to see all the accounts that begin with those letters which would show students. Now that seems to not be showing up anymore. Is this intentional or a bug?

**Comment by drlippman** [comment]
Intentional. With 100k+ user accounts on our big servers, selecting one of those letters would cause a huge data pull and crash the browser.
I added the user lookup admin utility as an easier to find users. I still need to add some additional features one of these days.
On Feb 3, 2016 3:30 PM, ericvanboven <notifications@github.com> wrote:Used to be able to select the dropdown box under the listing of the users on the admin page and it used to have A-Z letters to be able to see all the accounts that begin with those letters which would show students Now that seems to not be showing up anymore Is this intentional or a bug?

**Comment by ericvanboven** [comment]
Thank you for the info. Figured as such, will let our faculty know.
