### ISSUE TITLE
feedback not loading

### ISSUE THREAD

**Issue by akuyper** [drlippman/IMathAS#198]
I have an issue for one course where feedback will not appear:

Click on Viewed scored assessment
<img width="424" alt="Screen Shot 2020-10-18 at 11 43 58 AM" src="https://user-images.githubusercontent.com/37995713/96374319-a55ad900-1137-11eb-9e66-e79cee583a44.png">

And it simply gets stuck on loading:
<img width="341" alt="Screen Shot 2020-10-18 at 11 44 09 AM" src="https://user-images.githubusercontent.com/37995713/96374317-a12ebb80-1137-11eb-8b8c-7ae1ed6dfbf5.png">

I do not have this issue for any of my other courses. Thank you for any help or suggestions.

**Comment by drlippman** [comment]
The presence of the "LTI Home" in the picture suggests that you are accessing this as a teacher.  If that's the case, the "View scored assessment" button shouldn't even be showing to you, since teachers don't have scored assessments.  I can only guess that's the issue.

If this is on your own install, I'd suggest checking your error logs to see if there's something else going on.  If this is on MyOpenMath, please message me on MOM or post in the forums there when you run into problems, rather than posting in github.  If you message me in MOM the course ID and assignment, I can try to look into it.

**Comment by akuyper** [comment]
Thanks for the quick response.

I was accessing and viewing the assignment through Canvas in student view. Guessing that is what is causing the confusion. Which is weird because it doesn't happen in my other courses when I tested this out in student view. 

It is just for this course that we are having issue with the feedback getting stuck on loading for students.

Anyway, it is on our own install so I will check error logs to see the issue. Appreciate the help
