### ISSUE TITLE
allowfullscreen is filtered in addinlinetext

### ISSUE THREAD

**Issue by cooplogic** [drlippman/IMathAS#42]
I am trying to determine what is causing the allowfullscreen code to be filtered when adding an embedded youtube video. The editor accepts the edit, but when the code is submitted the allowfullscreen code is removed from the html. It appears that it would be happening when the code is submitted, in which case htmLawed is most likely the cause from line 105:

```
	$htmlawedconfig = array('elements'=>'*-script');
$_POST['text'] = addslashes(htmLawed(stripslashes($_POST['text']),$htmlawedconfig));

```

However the filter shouldn't change the allowfullscreen code. So, there must be something happening before that, but I can't find the code. Any pointers about where to look would be great.

**Comment by drlippman** [comment]
From [this site](http://www.bioinformatics.org/phplabware/forum/viewtopic.php?id=261), "htmLawed does remove the 'allowscriptaccess' and 'allowfullscreen' attributes of the 'embed' element, which is expected as those attributes are not in the HTML specs."

It does appear, though, that the latest version of htmLawed has added allowfullscreen for iframes because of it's common use.  I'll look at updating the version imathas is using.
