### ISSUE TITLE
AJAX Question Save

### ISSUE THREAD

**Issue by gksander** [drlippman/IMathAS#63]
This isn't an issue, just a thought. (Redirect me if there's a better place for this.)

I've been thinking it'd be nice if there was a "Quick Save" option in the question authoring environment that essentially does the same thing as "Save and Test Question," but via AJAX so a page reload isn't required (on the authoring page). Maybe add a keybinding to call the method? 

Have you thought about this at all? Is there any good reasons *not* to implement something like this? If not, I think I might take a stab at trying to implement something along these lines. I think this type of "hot-push" workflow could be really useful when authoring questions.

**Comment by drlippman** [comment]
It's certainly a reasonable idea.  The reason it's not AJAX now is because I didn't know how to do it 10 years ago when I originally wrote that page ;)  My main reason for not going to AJAX saves when I write new pages has mainly been consistency in UI/UX - so that every page behaves the same.

But "Save and Test Question" is a place where you don't want to leave to page, so an AJAX save makes a lot of sense.  If you want to take a stab at implementing it, go for it :)

**Comment by gksander** [comment]
So I've got the AJAX functionality working (thanks, jQuery). It didn't require too much additional code. I have a couple questions though:

1. Currently I'm binding the "quick save" method to buttons placed by the other save buttons, as well as Ctrl + Shift + S keypress event. I like the idea of binding the method to a key event (to make it easy and quick to use). Is there any issues with using Ctrl + Shift + S? Is there a better key combo?
2. Should I put some kind of "saving" notification as the AJAX completes the call? And maybe some kind of notification if save failed for whatever reason? If so -- do you have any preference on where this should go/what it should look like?

**Comment by drlippman** [comment]
BTW, make sure your save functionality includes fetching content from tinymce if it's been enabled on the question text field.

Yes, some kind of saving notification would be appropriate, as well as some sort of error reporting if something goes wrong.  On other AJAX-save pages, we've put it after the save button, using the noticetext class.  You could include img/updating.gif if you want or just a "Saving..." note, which goes away after a successful save, or is replaced with an error if there's a failure.

I don't feel strongly about adding a keyboard shortcut. It seems pretty unnecessary to me, but it doesn't seem like it'd do any harm.  Since tinymce already hijacks Ctrl/Cmd+S, maybe we should just use that too, since it's a more familiar shortcut for saving and I doubt that anyone would be wanting to use the browser default save behavior on that page.
