### ISSUE TITLE
Bug in file uploads

### ISSUE THREAD

**Issue by ericvanboven** [drlippman/IMathAS#84]
After doing a code update, file uploads seem to have a bug. I upload a file/images say images.jpeg the link in imathas will say the correct path filestore/ufiles/22088/images.jpeg but the file that got uploaded will be ufiles22088images.jpeg instead of images.jpeg.

**Comment by drlippman** [comment]
Uh oh, looks like someone got overzealous with the filename sanitizer. I'll work on a fix tonight.On Jun 14, 2017 2:38 PM, ericvanboven <notifications@github.com> wrote:After doing a code update, file uploads seem to have a bug. I upload a file/images say images.jpeg the link in imathas will say the correct path filestore/ufiles/22088/images.jpeg but the file that got uploaded will be ufiles22088images.jpeg instead of images.jpeg.
